#!/bin/bash
export ROOTPATH="$(dirname "$(readlink -f "$0")")/.."

# Add the correct path to the LD_LIBRARY_PATH enviroment variable
export LD_LIBRARY_PATH=$ROOTPATH/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$ROOTPATH/custom_libs:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$ROOTPATH/Qt-5.9.1/lib:$LD_LIBRARY_PATH
NOSETESTS="$ROOTPATH/bin/mlc_python $ROOTPATH/bin/nosetests"

# Run the dynamically compiled nosetests
if [ "$#" -ne 0 ]; then
        $NOSETESTS $@
else
        $NOSETESTS
fi
