#!/bin/bash
export ROOTPATH="$(dirname "$(readlink -f "$0")")/.."

# Add the correct path to the LD_LIBRARY_PATH enviroment variable
export PATH=$ROOTPATH/custom_bins:$PATH
export LD_LIBRARY_PATH=$ROOTPATH/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$ROOTPATH/custom_libs:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$ROOTPATH/Qt-5.9.1/lib:$LD_LIBRARY_PATH
PYTHON="$ROOTPATH/bin/python3.4"

# Run the dynamically compiled python for matlab
if [ "$#" -ne 0 ]; then
        $PYTHON $@
else
        $PYTHON
fi
