# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './untitled/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MLCManager(object):
    def setupUi(self, MLCManager):
        MLCManager.setObjectName("MLCManager")
        MLCManager.setWindowModality(QtCore.Qt.ApplicationModal)
        MLCManager.resize(749, 585)
        self.centralWidget = QtWidgets.QWidget(MLCManager)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.projects_box = QtWidgets.QGroupBox(self.centralWidget)
        self.projects_box.setObjectName("projects_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.projects_box)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.projects_box)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.open_button = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_button.sizePolicy().hasHeightForWidth())
        self.open_button.setSizePolicy(sizePolicy)
        self.open_button.setObjectName("open_button")
        self.gridLayout.addWidget(self.open_button, 2, 0, 1, 1)
        self.new_button = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_button.sizePolicy().hasHeightForWidth())
        self.new_button.setSizePolicy(sizePolicy)
        self.new_button.setObjectName("new_button")
        self.gridLayout.addWidget(self.new_button, 0, 0, 1, 1)
        self.import_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_button.sizePolicy().hasHeightForWidth())
        self.import_button.setSizePolicy(sizePolicy)
        self.import_button.setObjectName("import_button")
        self.gridLayout.addWidget(self.import_button, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 2)
        self.clone_button = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clone_button.sizePolicy().hasHeightForWidth())
        self.clone_button.setSizePolicy(sizePolicy)
        self.clone_button.setObjectName("clone_button")
        self.gridLayout.addWidget(self.clone_button, 2, 1, 1, 1)
        self.remove_button = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_button.sizePolicy().hasHeightForWidth())
        self.remove_button.setSizePolicy(sizePolicy)
        self.remove_button.setObjectName("remove_button")
        self.gridLayout.addWidget(self.remove_button, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.export_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_button.sizePolicy().hasHeightForWidth())
        self.export_button.setSizePolicy(sizePolicy)
        self.export_button.setObjectName("export_button")
        self.gridLayout.addWidget(self.export_button, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.experiment_list = QtWidgets.QListView(self.projects_box)
        self.experiment_list.setObjectName("experiment_list")
        self.verticalLayout.addWidget(self.experiment_list)
        self.horizontalLayout.addWidget(self.projects_box)
        self.description_box = QtWidgets.QGroupBox(self.centralWidget)
        self.description_box.setObjectName("description_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.description_box)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.experiment_description = QtWidgets.QTextBrowser(self.description_box)
        self.experiment_description.setObjectName("experiment_description")
        self.horizontalLayout_2.addWidget(self.experiment_description)
        self.horizontalLayout.addWidget(self.description_box)
        MLCManager.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MLCManager)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 749, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuMLC = QtWidgets.QMenu(self.menuBar)
        self.menuMLC.setObjectName("menuMLC")
        self.menuProperties = QtWidgets.QMenu(self.menuBar)
        self.menuProperties.setObjectName("menuProperties")
        MLCManager.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MLCManager)
        self.statusBar.setObjectName("statusBar")
        MLCManager.setStatusBar(self.statusBar)
        self.menu_properties = QtWidgets.QAction(MLCManager)
        self.menu_properties.setObjectName("menu_properties")
        self.menu_close = QtWidgets.QAction(MLCManager)
        self.menu_close.setObjectName("menu_close")
        self.menu_about = QtWidgets.QAction(MLCManager)
        self.menu_about.setObjectName("menu_about")
        self.menuMLC.addAction(self.menu_properties)
        self.menuMLC.addSeparator()
        self.menuMLC.addAction(self.menu_close)
        self.menuProperties.addAction(self.menu_about)
        self.menuBar.addAction(self.menuMLC.menuAction())
        self.menuBar.addAction(self.menuProperties.menuAction())

        self.retranslateUi(MLCManager)
        self.menu_close.triggered.connect(MLCManager.close)
        self.clone_button.clicked.connect(MLCManager.on_clone_button_clicked)
        self.new_button.clicked.connect(MLCManager.on_new_button_clicked)
        self.remove_button.clicked.connect(MLCManager.on_remove_button_clicked)
        self.open_button.clicked.connect(MLCManager.on_open_button_clicked)
        self.experiment_list.clicked['QModelIndex'].connect(MLCManager.on_experiment_list_clicked)
        self.menu_properties.triggered.connect(MLCManager.edit_gui_config)
        self.experiment_list.activated['QModelIndex'].connect(MLCManager.on_experiment_list_clicked)
        self.import_button.clicked.connect(MLCManager.on_import_button_clicked)
        self.export_button.clicked.connect(MLCManager.on_export_button_clicked)
        # QtCore.QMetaObject.connectSlotsByName(MLCManager)

    def retranslateUi(self, MLCManager):
        _translate = QtCore.QCoreApplication.translate
        MLCManager.setWindowTitle(_translate("MLCManager", "MLC Project Manager"))
        self.projects_box.setTitle(_translate("MLCManager", "Projects"))
        self.open_button.setText(_translate("MLCManager", "Open"))
        self.new_button.setText(_translate("MLCManager", "New"))
        self.import_button.setText(_translate("MLCManager", "Import"))
        self.clone_button.setText(_translate("MLCManager", "Clone"))
        self.remove_button.setText(_translate("MLCManager", "Remove"))
        self.export_button.setText(_translate("MLCManager", "Export"))
        self.description_box.setTitle(_translate("MLCManager", "Description"))
        self.menuMLC.setTitle(_translate("MLCManager", "MLC"))
        self.menuProperties.setTitle(_translate("MLCManager", "Help"))
        self.menu_properties.setText(_translate("MLCManager", "Properties"))
        self.menu_properties.setToolTip(_translate("MLCManager", "Manager Properties"))
        self.menu_close.setText(_translate("MLCManager", "Close"))
        self.menu_close.setToolTip(_translate("MLCManager", "Close MLC Manager"))
        self.menu_about.setText(_translate("MLCManager", "About"))
        self.menu_about.setToolTip(_translate("MLCManager", "Project Information"))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './untitled/experiment_in_progress.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExperimentInProgressDialog(object):
    def setupUi(self, ExperimentInProgressDialog):
        ExperimentInProgressDialog.setObjectName("ExperimentInProgressDialog")
        ExperimentInProgressDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ExperimentInProgressDialog.resize(611, 533)
        self.centralWidget = QtWidgets.QWidget(ExperimentInProgressDialog)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gen_label = QtWidgets.QLabel(self.groupBox_3)
        self.gen_label.setObjectName("gen_label")
        self.verticalLayout_3.addWidget(self.gen_label)
        self.gen_progress_bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.gen_progress_bar.setProperty("value", 24)
        self.gen_progress_bar.setObjectName("gen_progress_bar")
        self.verticalLayout_3.addWidget(self.gen_progress_bar)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.indiv_label = QtWidgets.QLabel(self.groupBox_3)
        self.indiv_label.setObjectName("indiv_label")
        self.verticalLayout_3.addWidget(self.indiv_label)
        self.indiv_progress_bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.indiv_progress_bar.setProperty("value", 24)
        self.indiv_progress_bar.setObjectName("indiv_progress_bar")
        self.verticalLayout_3.addWidget(self.indiv_progress_bar)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.picture_groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.picture_groupBox.setObjectName("picture_groupBox")
        self.picture_layout = QtWidgets.QVBoxLayout(self.picture_groupBox)
        self.picture_layout.setObjectName("picture_layout")
        self.log_check = QtWidgets.QCheckBox(self.picture_groupBox)
        self.log_check.setObjectName("log_check")
        self.picture_layout.addWidget(self.log_check)
        self.indiv_chart = QtWidgets.QTextEdit(self.picture_groupBox)
        self.indiv_chart.setObjectName("indiv_chart")
        self.picture_layout.addWidget(self.indiv_chart)
        self.verticalLayout.addWidget(self.picture_groupBox)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancel_button = QtWidgets.QPushButton(self.frame)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        ExperimentInProgressDialog.setCentralWidget(self.centralWidget)

        self.retranslateUi(ExperimentInProgressDialog)
        self.cancel_button.clicked.connect(ExperimentInProgressDialog.on_cancel_button_clicked)
        # QtCore.QMetaObject.connectSlotsByName(ExperimentInProgressDialog)

    def retranslateUi(self, ExperimentInProgressDialog):
        _translate = QtCore.QCoreApplication.translate
        ExperimentInProgressDialog.setWindowTitle(_translate("ExperimentInProgressDialog", "Experiment Evaluation"))
        self.groupBox_3.setTitle(_translate("ExperimentInProgressDialog", "Experiment Progress"))
        self.gen_label.setText(_translate("ExperimentInProgressDialog", "TextLabel"))
        self.indiv_label.setText(_translate("ExperimentInProgressDialog", "TextLabel"))
        self.picture_groupBox.setTitle(_translate("ExperimentInProgressDialog", "Individuals\' Costs"))
        self.log_check.setText(_translate("ExperimentInProgressDialog", "Log Scale"))
        self.cancel_button.setText(_translate("ExperimentInProgressDialog", "Stop Experiment"))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './untitled/experiment.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Experiment(object):
    def setupUi(self, Experiment):
        Experiment.setObjectName("Experiment")
        Experiment.setWindowModality(QtCore.Qt.ApplicationModal)
        Experiment.resize(961, 547)
        self.centralWidget = QtWidgets.QWidget(Experiment)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.experiment_tab = QtWidgets.QWidget()
        self.experiment_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.experiment_tab.setObjectName("experiment_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.experiment_tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.experiment_tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chart_conf_frame = QtWidgets.QFrame(self.frame_4)
        self.chart_conf_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chart_conf_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chart_conf_frame.setObjectName("chart_conf_frame")
        self.chart_conf_layout = QtWidgets.QHBoxLayout(self.chart_conf_frame)
        self.chart_conf_layout.setObjectName("chart_conf_layout")
        self.textEdit = QtWidgets.QTextEdit(self.chart_conf_frame)
        self.textEdit.setObjectName("textEdit")
        self.chart_conf_layout.addWidget(self.textEdit)
        self.verticalLayout_4.addWidget(self.chart_conf_frame)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.valid_points_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.valid_points_combo.setObjectName("valid_points_combo")
        self.gridLayout_6.addWidget(self.valid_points_combo, 8, 1, 1, 1)
        self.nan_value_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.nan_value_combo.setObjectName("nan_value_combo")
        self.gridLayout_6.addWidget(self.nan_value_combo, 7, 3, 1, 1)
        self.nan_color_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.nan_color_combo.setObjectName("nan_color_combo")
        self.gridLayout_6.addWidget(self.nan_color_combo, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 6, 2, 1, 1)
        self.overflow_value_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.overflow_value_combo.setObjectName("overflow_value_combo")
        self.gridLayout_6.addWidget(self.overflow_value_combo, 6, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.marker_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.marker_combo.setObjectName("marker_combo")
        self.gridLayout_6.addWidget(self.marker_combo, 0, 5, 1, 1)
        self.overflow_color_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.overflow_color_combo.setObjectName("overflow_color_combo")
        self.gridLayout_6.addWidget(self.overflow_color_combo, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 7, 2, 1, 1)
        self.max_cost_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.max_cost_combo.setObjectName("max_cost_combo")
        self.gridLayout_6.addWidget(self.max_cost_combo, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 4, 1, 1)
        self.min_cost_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.min_cost_combo.setObjectName("min_cost_combo")
        self.gridLayout_6.addWidget(self.min_cost_combo, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 9, 0, 1, 1)
        self.points_combo = QtWidgets.QComboBox(self.groupBox_7)
        self.points_combo.setObjectName("points_combo")
        self.gridLayout_6.addWidget(self.points_combo, 9, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.experiment_tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ev_edit_button = QtWidgets.QPushButton(self.groupBox_2)
        self.ev_edit_button.setObjectName("ev_edit_button")
        self.gridLayout_3.addWidget(self.ev_edit_button, 1, 2, 1, 1)
        self.preev_edit_button = QtWidgets.QPushButton(self.groupBox_2)
        self.preev_edit_button.setObjectName("preev_edit_button")
        self.gridLayout_3.addWidget(self.preev_edit_button, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.test_button = QtWidgets.QPushButton(self.groupBox_5)
        self.test_button.setObjectName("test_button")
        self.gridLayout_4.addWidget(self.test_button, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.test_label_result = QtWidgets.QLabel(self.groupBox_5)
        self.test_label_result.setFrameShape(QtWidgets.QFrame.Panel)
        self.test_label_result.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_label_result.setText("")
        self.test_label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.test_label_result.setObjectName("test_label_result")
        self.gridLayout_4.addWidget(self.test_label_result, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.test_indiv_edit = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_indiv_edit.sizePolicy().hasHeightForWidth())
        self.test_indiv_edit.setSizePolicy(sizePolicy)
        self.test_indiv_edit.setObjectName("test_indiv_edit")
        self.gridLayout_4.addWidget(self.test_indiv_edit, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.start_button = QtWidgets.QPushButton(self.groupBox_6)
        self.start_button.setObjectName("start_button")
        self.gridLayout_5.addWidget(self.start_button, 2, 1, 1, 1)
        self.to_gen_combo = QtWidgets.QComboBox(self.groupBox_6)
        self.to_gen_combo.setObjectName("to_gen_combo")
        self.gridLayout_5.addWidget(self.to_gen_combo, 1, 1, 1, 1)
        self.from_gen_combo = QtWidgets.QComboBox(self.groupBox_6)
        self.from_gen_combo.setObjectName("from_gen_combo")
        self.gridLayout_5.addWidget(self.from_gen_combo, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.tabWidget.addTab(self.experiment_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_frame = QtWidgets.QFrame(self.tab)
        self.left_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_frame.setObjectName("left_menu_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.left_menu_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_14 = QtWidgets.QFrame(self.left_menu_frame)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.chart_layout = QtWidgets.QVBoxLayout(self.frame_14)
        self.chart_layout.setObjectName("chart_layout")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_14)
        self.textEdit_2.setObjectName("textEdit_2")
        self.chart_layout.addWidget(self.textEdit_2)
        self.verticalLayout_7.addWidget(self.frame_14)
        self.db_view = QtWidgets.QTableView(self.left_menu_frame)
        self.db_view.setObjectName("db_view")
        self.verticalLayout_7.addWidget(self.db_view)
        self.horizontalLayout_5.addWidget(self.left_menu_frame)
        self.right_menu_frame = QtWidgets.QFrame(self.tab)
        self.right_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu_frame.setObjectName("right_menu_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.right_menu_frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gen_count_group = QtWidgets.QGroupBox(self.right_menu_frame)
        self.gen_count_group.setObjectName("gen_count_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gen_count_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.prev_gen_button = QtWidgets.QPushButton(self.gen_count_group)
        self.prev_gen_button.setObjectName("prev_gen_button")
        self.gridLayout_2.addWidget(self.prev_gen_button, 1, 0, 1, 1)
        self.gen_count_combo = QtWidgets.QComboBox(self.gen_count_group)
        self.gen_count_combo.setObjectName("gen_count_combo")
        self.gridLayout_2.addWidget(self.gen_count_combo, 0, 0, 1, 2)
        self.next_gen_button = QtWidgets.QPushButton(self.gen_count_group)
        self.next_gen_button.setObjectName("next_gen_button")
        self.gridLayout_2.addWidget(self.next_gen_button, 1, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.gen_count_group)
        self.groupBox_4 = QtWidgets.QGroupBox(self.right_menu_frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.log_check = QtWidgets.QCheckBox(self.groupBox_4)
        self.log_check.setObjectName("log_check")
        self.verticalLayout_12.addWidget(self.log_check)
        self.show_all_check = QtWidgets.QCheckBox(self.groupBox_4)
        self.show_all_check.setObjectName("show_all_check")
        self.verticalLayout_12.addWidget(self.show_all_check)
        self.dimension_check = QtWidgets.QCheckBox(self.groupBox_4)
        self.dimension_check.setObjectName("dimension_check")
        self.verticalLayout_12.addWidget(self.dimension_check)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.right_menu_frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_13.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_13.addWidget(self.pushButton_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_13.addWidget(self.pushButton_8)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.right_menu_frame)
        self.tabWidget.addTab(self.tab, "")
        self.config_tab = QtWidgets.QWidget()
        self.config_tab.setObjectName("config_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.config_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.config_tab)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.config_table = QtWidgets.QTableView(self.groupBox)
        self.config_table.setObjectName("config_table")
        self.config_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.config_table)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.import_config_button = QtWidgets.QPushButton(self.frame_2)
        self.import_config_button.setObjectName("import_config_button")
        self.horizontalLayout_7.addWidget(self.import_config_button)
        self.export_config_button = QtWidgets.QPushButton(self.frame_2)
        self.export_config_button.setObjectName("export_config_button")
        self.horizontalLayout_7.addWidget(self.export_config_button)
        self.save_config_button = QtWidgets.QPushButton(self.frame_2)
        self.save_config_button.setObjectName("save_config_button")
        self.horizontalLayout_7.addWidget(self.save_config_button)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.tabWidget.addTab(self.config_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        Experiment.setCentralWidget(self.centralWidget)

        self.retranslateUi(Experiment)
        self.tabWidget.setCurrentIndex(0)
        self.next_gen_button.clicked.connect(Experiment.on_next_gen_button_clicked)
        self.save_config_button.clicked.connect(Experiment.on_save_config_button_clicked)
        self.dimension_check.clicked.connect(Experiment.on_dimension_check_clicked)
        self.show_all_check.clicked.connect(Experiment.on_show_all_check_clicked)
        self.tabWidget.currentChanged['int'].connect(Experiment.on_tab_changed)
        self.log_check.clicked.connect(Experiment.on_log_check_clicked)
        self.preev_edit_button.clicked.connect(Experiment.on_preev_edit_button_clicked)
        self.test_button.clicked.connect(Experiment.on_test_button_clicked)
        self.prev_gen_button.clicked.connect(Experiment.on_prev_gen_button_clicked)
        self.gen_count_combo.activated['QString'].connect(Experiment.on_gen_count_combo_changed)
        self.ev_edit_button.clicked.connect(Experiment.on_ev_edit_button_clicked)
        self.start_button.clicked.connect(Experiment.on_start_button_clicked)
        self.valid_points_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        self.overflow_color_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        self.points_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        self.marker_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        self.overflow_value_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        self.nan_value_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        self.min_cost_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        self.max_cost_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        self.nan_color_combo.currentTextChanged['QString'].connect(Experiment.on_chart_config_changed)
        # QtCore.QMetaObject.connectSlotsByName(Experiment)

    def retranslateUi(self, Experiment):
        _translate = QtCore.QCoreApplication.translate
        Experiment.setWindowTitle(_translate("Experiment", "Dialog"))
        self.groupBox_7.setTitle(_translate("Experiment", "Chart Configuration"))
        self.label_12.setText(_translate("Experiment", "Overflow Value:"))
        self.label_7.setText(_translate("Experiment", "Max Cost:"))
        self.label_8.setText(_translate("Experiment", "Overflow Color:"))
        self.label_11.setText(_translate("Experiment", "Min Cost:"))
        self.label_10.setText(_translate("Experiment", "NaN/Inf Color:"))
        self.label_13.setText(_translate("Experiment", "NaN/Inf Value:"))
        self.label_14.setText(_translate("Experiment", "Marker Size:"))
        self.label_9.setText(_translate("Experiment", "Valid Points Color:"))
        self.label_15.setText(_translate("Experiment", "Visualized Points:"))
        self.groupBox_2.setTitle(_translate("Experiment", "Scripts"))
        self.ev_edit_button.setText(_translate("Experiment", "Edit"))
        self.preev_edit_button.setText(_translate("Experiment", "Edit"))
        self.label_3.setText(_translate("Experiment", "Preevaluation Script:"))
        self.label_4.setText(_translate("Experiment", "Evaluation Script:"))
        self.groupBox_5.setTitle(_translate("Experiment", "Evaluation"))
        self.test_button.setText(_translate("Experiment", "Test"))
        self.label.setText(_translate("Experiment", "Test Result:"))
        self.label_2.setText(_translate("Experiment", "Test Individual:"))
        self.groupBox_6.setTitle(_translate("Experiment", "Experiment"))
        self.start_button.setText(_translate("Experiment", "Start Experiment"))
        self.label_5.setText(_translate("Experiment", "To Generation:"))
        self.label_6.setText(_translate("Experiment", "From Generation:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.experiment_tab), _translate("Experiment", "Experiment"))
        self.gen_count_group.setTitle(_translate("Experiment", "Generation 0/0"))
        self.prev_gen_button.setText(_translate("Experiment", "<<"))
        self.next_gen_button.setText(_translate("Experiment", ">>"))
        self.groupBox_4.setTitle(_translate("Experiment", "Graph Options"))
        self.log_check.setText(_translate("Experiment", "Log"))
        self.show_all_check.setText(_translate("Experiment", "Show All"))
        self.dimension_check.setText(_translate("Experiment", "3D"))
        self.groupBox_3.setTitle(_translate("Experiment", "DB"))
        self.pushButton_3.setText(_translate("Experiment", "Create"))
        self.pushButton_4.setText(_translate("Experiment", "Cut"))
        self.pushButton_8.setText(_translate("Experiment", "Import"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Experiment", "Results"))
        self.groupBox.setTitle(_translate("Experiment", "Experiment properties"))
        self.import_config_button.setText(_translate("Experiment", "Import"))
        self.export_config_button.setText(_translate("Experiment", "Export"))
        self.save_config_button.setText(_translate("Experiment", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_tab), _translate("Experiment", "Configuration"))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './untitled/edit_properties.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PropertiesDialog(object):
    def setupUi(self, PropertiesDialog):
        PropertiesDialog.setObjectName("PropertiesDialog")
        PropertiesDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PropertiesDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(PropertiesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(PropertiesDialog)
        self.tableView.setFrameShape(QtWidgets.QFrame.HLine)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableView)
        self.buttonBox = QtWidgets.QDialogButtonBox(PropertiesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PropertiesDialog)
        self.buttonBox.accepted.connect(PropertiesDialog.accept)
        self.buttonBox.rejected.connect(PropertiesDialog.reject)
        # QtCore.QMetaObject.connectSlotsByName(PropertiesDialog)

    def retranslateUi(self, PropertiesDialog):
        _translate = QtCore.QCoreApplication.translate
        PropertiesDialog.setWindowTitle(_translate("PropertiesDialog", "MLC Manager Properties"))

