import os
import re
import sys
import subprocess

mlc_pyuic5_path = '/opt/mlc-python-2.7.11/bin/mlc_pyuic'
qtcreator_dir = './untitled'
autogenerate_file = "./autogenerated.py"

# Get all the .ui from the QtCreator project
files = os.listdir(qtcreator_dir)
r = re.compile(r'^.*\.ui$')
files_to_autogenerate = [file for file in files if r.search(file)]

if not files_to_autogenerate:
    print "There are no files to be processed. Aborting program"
    sys.exit(0)

with open(autogenerate_file, "w") as f:
    for file in files_to_autogenerate:
        command = mlc_pyuic5_path + " " + qtcreator_dir + "/" + file
        ret = subprocess.call(command, shell=True, stdout=f)

# Comment the connectSlotsByName line in all files
data = ""
with open(autogenerate_file, "r") as f:
    data = f.read()

data = data.replace("QtCore.QMetaObject.connectSlotsByName", "# QtCore.QMetaObject.connectSlotsByName")
with open(autogenerate_file, "w") as f:
    f.write(data)
