# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board_config_design.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BoardConfigurationFrame(object):
    def setupUi(self, BoardConfigurationFrame):
        BoardConfigurationFrame.setObjectName("BoardConfigurationFrame")
        BoardConfigurationFrame.resize(783, 590)
        self.centralWidget = QtWidgets.QWidget(BoardConfigurationFrame)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boardTypeSelectorFrame = QtWidgets.QFrame(self.frame_2)
        self.boardTypeSelectorFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.boardTypeSelectorFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.boardTypeSelectorFrame.setObjectName("boardTypeSelectorFrame")
        self.formLayout = QtWidgets.QFormLayout(self.boardTypeSelectorFrame)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.boardTypeSelectorFrame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.arduinoBoard = QtWidgets.QComboBox(self.boardTypeSelectorFrame)
        self.arduinoBoard.setMinimumSize(QtCore.QSize(500, 0))
        self.arduinoBoard.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.arduinoBoard.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.arduinoBoard.setIconSize(QtCore.QSize(16, 16))
        self.arduinoBoard.setFrame(True)
        self.arduinoBoard.setModelColumn(0)
        self.arduinoBoard.setObjectName("arduinoBoard")
        self.arduinoBoard.addItem("")
        self.arduinoBoard.addItem("")
        self.arduinoBoard.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.arduinoBoard)
        self.label_2 = QtWidgets.QLabel(self.boardTypeSelectorFrame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.arduinoInterface = QtWidgets.QLineEdit(self.boardTypeSelectorFrame)
        self.arduinoInterface.setObjectName("arduinoInterface")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.arduinoInterface)
        self.verticalLayout_2.addWidget(self.boardTypeSelectorFrame)
        self.horizontalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(11, 0, 11, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.showPinout = QtWidgets.QPushButton(self.frame_3)
        self.showPinout.setObjectName("showPinout")
        self.verticalLayout_3.addWidget(self.showPinout)
        self.testInterface = QtWidgets.QPushButton(self.frame_3)
        self.testInterface.setObjectName("testInterface")
        self.verticalLayout_3.addWidget(self.testInterface)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.digitalPins = QtWidgets.QComboBox(self.frame_4)
        self.digitalPins.setObjectName("digitalPins")
        self.digitalPins.addItem("")
        self.digitalPins.addItem("")
        self.digitalPins.addItem("")
        self.horizontalLayout_3.addWidget(self.digitalPins)
        self.digitalPinType = QtWidgets.QComboBox(self.frame_4)
        self.digitalPinType.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.digitalPinType.setFont(font)
        self.digitalPinType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.digitalPinType.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.digitalPinType.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.digitalPinType.setDuplicatesEnabled(False)
        self.digitalPinType.setFrame(True)
        self.digitalPinType.setObjectName("digitalPinType")
        self.digitalPinType.addItem("")
        self.digitalPinType.addItem("")
        self.digitalPinType.addItem("")
        self.horizontalLayout_3.addWidget(self.digitalPinType)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.addDigitalPin = QtWidgets.QPushButton(self.groupBox_2)
        self.addDigitalPin.setObjectName("addDigitalPin")
        self.verticalLayout_4.addWidget(self.addDigitalPin)
        self.digitalPinsList = QtWidgets.QTableWidget(self.groupBox_2)
        self.digitalPinsList.setObjectName("digitalPinsList")
        self.digitalPinsList.setColumnCount(2)
        self.digitalPinsList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.digitalPinsList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.digitalPinsList.setHorizontalHeaderItem(1, item)
        self.digitalPinsList.horizontalHeader().setCascadingSectionResizes(True)
        self.digitalPinsList.horizontalHeader().setDefaultSectionSize(150)
        self.digitalPinsList.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.digitalPinsList)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.analogPins = QtWidgets.QComboBox(self.frame_6)
        self.analogPins.setObjectName("analogPins")
        self.analogPins.addItem("")
        self.analogPins.addItem("")
        self.analogPins.addItem("")
        self.horizontalLayout_4.addWidget(self.analogPins)
        self.analogPinType = QtWidgets.QComboBox(self.frame_6)
        self.analogPinType.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.analogPinType.setFont(font)
        self.analogPinType.setObjectName("analogPinType")
        self.analogPinType.addItem("")
        self.analogPinType.addItem("")
        self.horizontalLayout_4.addWidget(self.analogPinType)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.addPin = QtWidgets.QPushButton(self.frame_5)
        self.addPin.setObjectName("addPin")
        self.verticalLayout_6.addWidget(self.addPin)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.analogPinList = QtWidgets.QTableWidget(self.groupBox_3)
        self.analogPinList.setObjectName("analogPinList")
        self.analogPinList.setColumnCount(2)
        self.analogPinList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.analogPinList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.analogPinList.setHorizontalHeaderItem(1, item)
        self.analogPinList.horizontalHeader().setCascadingSectionResizes(True)
        self.analogPinList.horizontalHeader().setDefaultSectionSize(150)
        self.analogPinList.horizontalHeader().setHighlightSections(True)
        self.analogPinList.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.analogPinList)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.frame)
        self.frame_7 = QtWidgets.QFrame(self.centralWidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(10, 1, 10, 1)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.benchTests = QtWidgets.QPushButton(self.frame_7)
        self.benchTests.setObjectName("benchTests")
        self.horizontalLayout_5.addWidget(self.benchTests)
        self.cancelButton = QtWidgets.QPushButton(self.frame_7)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.acceptButton = QtWidgets.QPushButton(self.frame_7)
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_5.addWidget(self.acceptButton)
        self.verticalLayout.addWidget(self.frame_7)
        self.verticalLayout.setStretch(1, 1)
        BoardConfigurationFrame.setCentralWidget(self.centralWidget)

        self.retranslateUi(BoardConfigurationFrame)
        QtCore.QMetaObject.connectSlotsByName(BoardConfigurationFrame)

    def retranslateUi(self, BoardConfigurationFrame):
        _translate = QtCore.QCoreApplication.translate
        BoardConfigurationFrame.setWindowTitle(_translate("BoardConfigurationFrame", "MainWindow"))
        self.groupBox.setTitle(_translate("BoardConfigurationFrame", "Board Selection"))
        self.label.setText(_translate("BoardConfigurationFrame", "Type"))
        self.arduinoBoard.setItemText(0, _translate("BoardConfigurationFrame", "Arduino Due"))
        self.arduinoBoard.setItemText(1, _translate("BoardConfigurationFrame", "Arduino Uno"))
        self.arduinoBoard.setItemText(2, _translate("BoardConfigurationFrame", "Arduino Mega"))
        self.label_2.setText(_translate("BoardConfigurationFrame", "Interface"))
        self.arduinoInterface.setText(_translate("BoardConfigurationFrame", "/dev/ttyACM0"))
        self.showPinout.setText(_translate("BoardConfigurationFrame", "Show board Pinout"))
        self.testInterface.setText(_translate("BoardConfigurationFrame", "Test Interface"))
        self.groupBox_2.setTitle(_translate("BoardConfigurationFrame", "Digital Pins"))
        self.digitalPins.setItemText(0, _translate("BoardConfigurationFrame", "Pin 1"))
        self.digitalPins.setItemText(1, _translate("BoardConfigurationFrame", "Pin 2"))
        self.digitalPins.setItemText(2, _translate("BoardConfigurationFrame", "Pin 3"))
        self.digitalPinType.setItemText(0, _translate("BoardConfigurationFrame", "input"))
        self.digitalPinType.setItemText(1, _translate("BoardConfigurationFrame", "output"))
        self.digitalPinType.setItemText(2, _translate("BoardConfigurationFrame", "pwm"))
        self.addDigitalPin.setText(_translate("BoardConfigurationFrame", "Add Pin"))
        item = self.digitalPinsList.horizontalHeaderItem(0)
        item.setText(_translate("BoardConfigurationFrame", "Pin"))
        item = self.digitalPinsList.horizontalHeaderItem(1)
        item.setText(_translate("BoardConfigurationFrame", "Type"))
        self.groupBox_3.setTitle(_translate("BoardConfigurationFrame", "Analog Pins"))
        self.analogPins.setItemText(0, _translate("BoardConfigurationFrame", "Pin A0"))
        self.analogPins.setItemText(1, _translate("BoardConfigurationFrame", "Pin A1"))
        self.analogPins.setItemText(2, _translate("BoardConfigurationFrame", "Pin A2"))
        self.analogPinType.setItemText(0, _translate("BoardConfigurationFrame", "input"))
        self.analogPinType.setItemText(1, _translate("BoardConfigurationFrame", "output"))
        self.addPin.setText(_translate("BoardConfigurationFrame", "Add Pin"))
        item = self.analogPinList.horizontalHeaderItem(0)
        item.setText(_translate("BoardConfigurationFrame", "Pin"))
        item = self.analogPinList.horizontalHeaderItem(1)
        item.setText(_translate("BoardConfigurationFrame", "Type"))
        self.benchTests.setText(_translate("BoardConfigurationFrame", "Bechmarking tests"))
        self.cancelButton.setText(_translate("BoardConfigurationFrame", "Cancel"))
        self.acceptButton.setText(_translate("BoardConfigurationFrame", "Accept"))

